### ISSUE TITLE
Error: String Indices must be integers 

### ISSUE THREAD

**Issue by joecarav** [ajmarks/sharkiq#17]
Hi, 

Just trying to run this to confirm I can sign in: 

```
from sharkiqpy import get_ayla_api, OperatingModes, Properties, PowerModes

USERNAME = 'my_username'
PASSWORD = 'my_password'

ayla_api = get_ayla_api(USERNAME, PASSWORD)
ayla_api.sign_in()
```

and I am receiving this error: 

```
Traceback (most recent call last):
  File "/Users/cartnj/Desktop/usefulprojects/vacuum.py", line 7, in <module>
    ayla_api.sign_in()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sharkiqpy/ayla_api.py", line 84, in sign_in
    self._set_credentials(resp.status_code, resp.json())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sharkiqpy/ayla_api.py", line 73, in _set_credentials
    raise SharkIqAuthError(login_result["error"]["message"])
TypeError: string indices must be integers
```

Any ideas? I just started playing with this API so I apologize if I am missing something. Thanks in advance!

**Comment by DTFagus** [comment]
Same for me... Same when using python script or the home assistant integration.

**Comment by TheLastFrame** [comment]
Hey,
since the owner of this repo hasn't really maintained it anymore a new one was created here: https://github.com/JeffResc/sharkiq

Please test if the issue also persists with this version. If so please open an issue there.
